name: Awesome-CI

on: [push]

jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wsoula/awesome-cv-action@0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        FILE_NAME: 'wsoula.tex'
